### ISSUE TITLE
R CMD check fails on CRAN

### ISSUE THREAD

**Issue by Bisaloo** [epiforecasts/idbrms#6]
Spotted thanks to R-universe: https://github.com/r-universe/epiforecasts/runs/2765209598?check_suite_focus=true

You can reproduce locally by running:

```r
devtools::check(env_vars = NULL)
```

> Error: could not find function "calc_unique_pmfs"

This is expected since https://github.com/epiforecasts/idbrms/blob/159c8d5c507a1c738627735866d2e37ff35662d4/tests/testthat/test-stan-calc_unique_pmfs.R#L3-L12 never runs on CRAN.

I'm not sure how to fix it because I don't know why it is necessary to wrap these lines with `if (!testthat:::on_cran()) { ... }`

**Comment by seabbs** [comment]
This compiles stan code so takes a while and would make the tests take a while if used on CRAN. Any suggestions for a CRAN check that will work in a universe but will still skip this (but won't skip on other CI?)
